.TH "PETS\-CHECK" "1" "August 2022" "" ""
.SH "NAME"
\fBpets-check\fR \- Check if a "db\.json" file exists\.
.SH SYNOPSIS
.P
.RS 2
.nf
$ pets check [path]
.fi
.RE
.SH DESCRIPTION
.P
Checks if a "db\.json" file exists in a given file path\. If \fBpath\fP is not specified, it is the current directory\.

