.TH "PETS\-HELP" "1" "August 2022" "" ""
.SH "NAME"
\fBpets-help\fR \- help utility
.P
.RS 2
.nf

$ pets help [command]


Usage example: lounger help config
.fi
.RE
.SH DESCRIPTION
.P
Displays a general purpose help utility if \fBcommand\fP is not supplied
.P
\fBcommand\fP is an optional argument that when supplied, spawns up help content relating to that particular command

